export enum Status {
	UPLOADING = 0,
	SAVING_THUMBNAIL = 1,
	SAVING_VIDEO = 2,
	UPLOADING_SUCCES = 3,
	UPLOADING_ERROR = 4,

	ANALYZING = 1,
	ANALYZING_SUCCES = 2,
	ANALYZING_FAIL = -1,

	SUBMITTING = 1,
	SUBMITTING_SUCCESS = 2,
	SUBMITTING_FAIL = -1
}

export default Status;
